---
title: "tidytrials: from search to plot"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{tidytrials: from search to plot}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### 1. Load the packages

```{r}
library(tidytrials)
library(dplyr)
library(ggplot2)
```

### 2. Search Studies

```{r}
res <- trials_fetch(
  query = "diabetes",
  max_records = 50
)

class(res$studies)
```
### 2b. Search studies convert to JSON output
```{r}
res_json <- trials_fetch(
  query = "diabetes",
  max_records = 50, save_json =TRUE,json_file="test.json"
)
json_output <- jsonlite::fromJSON(("test.json"), simplifyVector = FALSE)

```


### 3. Convert to tidy module tables

```{r}
tabs <- studies_to_tables_by_module(
  res,
  modules = c("statusModule", "designModule")
)
status <- tabs$statusModule
design <- tabs$designModule

status
```
### 3b. convert json output to tidy modules tables

```{r}
tabs <- studies_to_tables_by_module(
  json_output,
  modules = c("statusModule", "designModule")
)
status <- tabs$statusModule
design <- tabs$designModule

status

```


### 4. Plot: recruiting status distribution

```{r}
status |>
  filter(!is.na(overall_status)) |>
  count(overall_status, sort = TRUE) |>
  ggplot(aes(x = reorder(overall_status, n), y = n)) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Clinical trials by overall status",
    x = "Overall status",
    y = "Number of trials"
  )
```

### 5. Plot by Phase Distribution

```{r}
design |>
  filter(!is.na(phases)) |>
  count(phases, sort = TRUE) |>
  ggplot(aes(x = reorder(phases, n), y = n)) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Clinical trials by phase",
    x = "Phase",
    y = "Number of trials"
  )

```

